cache:
    paths:
        - node_modules/

stages:
    - server_app_tests
    - deploy

server app unit tests:
    image: node:latest
    stage: server_app_tests
    only:
        - dev
    script:
        - echo "Running unit tests for server app ..."
        - sleep 10
        - echo "Unit tests for the server app were successfully passed."

server app lint tests:
    image: node:latest
    stage: server_app_tests
    only:
        - dev
    script:
        - echo "Running lint command for the server app ..."
        - sleep 10
        - echo "No lint issues found."

deploy to dev server:
    image: ubuntu
    stage: deploy
    only:
        - dev
    before_script:
        - echo "Deploying app on pozitronet.ir ..."
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_ed25519
        - chmod 600 ~/.ssh/id_ed25519
        - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
    script:
        - ssh $SERVER_USER@$SERVER_IP "cd /var/www/dev.pozitronet.ir && git reset --hard && git pull origin dev"
        - echo "App successfully deployed."

